services:
  db:
    container_name: trapper-db
    image: postgres:17.4
    hostname: postgres
    ports:
      - "127.0.0.1:5432:5432"
    env_file: "./.env"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tadmin -d trapper-db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: trapper-server
    build:
      context: server
    ports:
      - "127.0.0.1:8000:8000" # Expose to localhost only
    env_file: "./server/.env"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/home/appuser/trapper-server

volumes:
  db-data:
    driver: local
